"""This module provides an abstraction layer to loguru.

Since loguru works as a singleton, which is an anti-pattern,
this module will also follows the same.

You may have multiple instances of PropoesEvent 
and all methods works asyncronously.

Logs are registered only once on loguru's system, 
avoiding some undesirable behaviors.
"""

from loguru import logger

from src.web.schemas.poem import Poem

are_essential_logs_registered = False


def register_essential_logs() -> None:
    """Register all essential logs of the system.

    This includes requests, generated poems and user's feedback.
    All logs are saved into ``logs/`` folder.

    Logs
    ----
    feedback.log
        Store all feedbacks made by users. Use ``log_feedback`` to log it.

    poems.log
        Store all generated poems by Propoe. Use ``log_generated_poem`` to log it.

    request.log
        Store all requests made to the server. Use ``log_request`` to log it.

    """

    logger.add(
        "logs/request.log",
        format="{time:YYYY-MM-DD} | Action: Request at /{extra[route]}/ | {message}",
        encoding="UTF-8",
        filter=lambda record: "request" in record["extra"],
    )

    logger.add(
        "logs/poems.log",
        serialize=True,
        format="Poem generated!",
        encoding="UTF-8",
        filter=lambda record: "poem" in record["extra"],
    )

    logger.add(
        "logs/feedback.log",
        format="{time:YYYY-MM-DD} | Action: Feedback | ⭐ {extra[stars]} : {message}",
        encoding="UTF-8",
        filter=lambda record: "feedback" in record["extra"],
    )

    are_essential_logs_registered = True  # noqa: F841


class PropoesEvent:
    """System's logger"""

    def __init__(self) -> None:
        if not are_essential_logs_registered:
            register_essential_logs()

    @staticmethod
    async def route_requested(route: str, message: str) -> None:
        """Log server's requests

        Logs the request into ``logs/request.log``.

        Parameters
        ----------
        route: str
            The current route. Based on FastAPI's route.
            E.g.: "login"
        message: str
            A custom message to be displayed on log.

        """

        logger.bind(request=True).info(message, route=route)

    # Specific Loggings

    @staticmethod
    async def poem_created(generated_poem: Poem) -> None:
        """Log poems generated by Propoe.

        Logs the request into ``logs/poems.log``.
        All poems are serialized as Json.
        Use some script to clear and concatenate it later.

        Parameters
        ----------
        generated_poem: Poem
            The generated Poem that was returned to the user.

        """

        logger.bind(poem=True).info(generated_poem.model_dump())

    @staticmethod
    async def feedback_submited(comment: str, stars: int) -> None:
        """Log poems generated by Propoe.

        Logs user's feedback into ``logs/feedback.log``.
        All multilined comments are inlined replacing new lines by pilcrow.

        Parameters
        ----------
        comment: str
            Qualitative Propoe UX feedback.

        stars: int
            Quantitative Propoe UX feedback. A score between 1 and 5.

        """
        assert 1 <= stars <= 5

        inlined_comment = comment.replace("\n", "¶ ")
        logger.bind(feedback=True).info(inlined_comment, stars=stars)


__all__ = ["PropoesEvent"]
